Document: libapriltags
Title: Debian libapriltags Manual
Author: <insert document author here>
Abstract: This manual describes what libapriltags is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libapriltags/libapriltags.sgml.gz

Format: postscript
Files: /usr/share/doc/libapriltags/libapriltags.ps.gz

Format: text
Files: /usr/share/doc/libapriltags/libapriltags.text.gz

Format: HTML
Index: /usr/share/doc/libapriltags/html/index.html
Files: /usr/share/doc/libapriltags/html/*.html
